
#General Settings
[general]
	#If set to true, will allow the player to relight torches that are in the middle of burning. If set to false, torches must burn out before lighting again.
	torch_relightAllowed = false
	#The durability, in uses, of the flint and tinder.
	#Range: 1 ~ 64
	flintAndTinder_durability = 32
	#How many times maximum it can take for a flint and tinder to light a torch.
	#Range: 1 ~ 16
	flintAndTinder_maxStrikes = 4
	#If set to true, the world will generate with this mod's lit torches as opposed to vanilla torches. If set to false, vanilla torches will generate.
	worldGen_replaceTorches = true
	#The chance, every random tick, that a torch will dim and shed one less light level.
	#Range: 0.01 ~ 1.0
	torch_chanceToDim = 0.01
	#If set to true, will show what torches are updating and where they are in the world in the log. Will send lots of logging entries to the console.
	debug_showDebug = false
	#How much durability, in uses, the bow drill has.
	#Range: 1 ~ 128
	bowDrill_durability = 64
	#How many times maximum it can take for a bow drill to light a torch.
	#Range: 1 ~ 8
	bowDrill_maxStrikes = 2
	#If set to true, the generation will generate lit torches that eventually go out. If set to false, will generate unlit torches.
	worldGen_startLit = true

